listen_address: "0.0.0.0"
listen_port: 9000
ssl:
  enabled: true
  ca_path: "/Users/dwiyan/dwyn-project/dwiyan-projects/certs/sample.pem"
  key_path: "/Users/dwiyan/dwyn-project/dwiyan-projects/certs/sample.rsa"
logging:
  mode: "lll"
  trace_traffic: true
  file_path: "/tmp/"
  file_name: "novaflow.log"
domain_server:
  enabled: true
  config:
    - name: domain_1
      domain_name: testserver.com
      remote_address: "http://1.1.1.1"
virtual_server:
  enabled: true
  config:
    - name: "Backend1"
      path: /backend1
      remote_address: "https://www.example.com/"