listen_address: "0.0.0.0"
listen_port: 9000
virtual_server:
  - name: Backend App 1
    path: /backend1
    remote_address: "http://10.66.66.6"
  - name: Backend App 2 # dd
    path: /backend2
    remote_address: "http://0.0.0.0:3001"