listen_address: "0.0.0.0"
listen_port: 9000
ssl:
  enabled: false
  cert_path: "/path/to/cert.pem"
  key_path: "/path/to/key.pem"
  ca_path: "/path/to/ca.pem"
traffic_logging:
  enabled: true
  file_path: "/var/log/traffic.log"
policy_logging:
  enabled: true
  file_path: "/var/log/policy.log"
virtual_server:
  enabled: true
  config:
    - name: Backend App 1
      path: /backend1
      remote_address: "http://10.66.66.6"
    - name: Backend App 2 # dd
      path: /backend2
      remote_address: "http://0.0.0.0:3001"
virtual_domain:
  enabled: true
  config:
    - name: Frontend App 1
      domain: "frontend1.com"
      remote_address: "http://"